F000: 0B    //11 THE FIRST NUMBER
F001: 02    //05 THE SECOND NUMBER
F002: 05    //QUOTIENT
F003: 01    //REMAINDER

//CODE
LXI H,F000H     //HL<-F000H
MOV A,M         //ACC<-MEMORY
INX H           //HL++
MOV B,M         //B REG <- MEMEORY
CMP B           //COMPARING
JNC L1          //JUMP IF NO CARRY
MOV B,A         //B<-ACCUMULATOR
MOV A,M         //ACC<-B
L1:MVI C,00     //C REGISTER COMES INIT WITH 00
L2:SUB B           //SUBTRACT B FROM THE ACCUMULATOR
JC L3           //JUMP IF CARRY MEANS NEGATIVE IN REMAINDER
INR C           //INCREMENT THE VALUE OF C
JMP L2          //DIRECT JUMP TO SUB B FOR DIVISION OR REPEAT SUBTRACTION
L3:ADD B        //ADD WITH B; REMAINDER BECOMES POSITIVE
STA F003        //SHOWS THE REMAINDER
MOV A,C         //FOR GETTING THE VALUE OF QUOTIENT
STA F002        //SHOWS THE QUOTIENT
HLT