F000: 1     //1ST VALUE
F001: 2     M//2ND VALUE
F002: OUTPUT (F001 + F002)


//CODE GIVE ME THE FIBONACCI SERIES UPTO 10 TERMS
LXI H,F000H
MOV B,M         //B CONTAINS FIRST VALUE
INX H
MOV A,M        //ACC CONTAINS SECOND VALUE
INX H
MVI C,08H      //COUNTER INIT WITH 8 CZ FIRST 2 VALUE IS GET

L1:MOV M,A        //MOVE THE VALUE OF ACC TO MEMORY
MOV D,A        //ACC VAL LOADED IN D
ADD B          //THIS WILL BE THE NEXT NO. IN THE SERIES
MOV B,D        //OLD VAL OF ACC
INX H
DCR C
JNZ L1
HLT
