//FINDING THE MAXIMUM B/W N NUMBERS

F000: 4     ;TOTAL NUMBERS
F001: 02    
F002: 05    A,M
F003: 10
F004: 11

FF01: lowest VALUE

LXI H,F000H
MOV B,M         //ENTER THE TOTAL NUMBERS
INX H
MOV A,M         //PUT THE 1ST NO IN ACC
DCR B
L2:INX H           //MOVE ONE STEP
CMP M           //CHECK WHICH ONE IS MAX
JC L1          // CARRY MEANS RESULT POSITIVE, FIRST NO. GREATER
MOV A,M
L1:DCR B        //B GETS DECREMENTED
JMP L2
STA FF01H       //STORES THE LOWEST VAL
HLT