//count the numbers of even odd count
F000: 05    //NUMBER OF ENTRIES
F001: 09    M
F002: 06
F003: 0F
F004: 0A
F005: 03

FF01: //NUMBER OF EVEN
FF02: //NUMBER OF ODDS

//CODE
LXI H,F000H
MOV B,M         //B STORES THE TOTAL NUMBER OF ENTRIES
MVI A,00        //ACC GETS 00
MVI D,00        //ODD COUNT GETS 00  //POSITIVE
MVI E,00        //EVEN COUNT GETS 00  //NEGATIVE
L3:INX H           //HL PAIR MOVES ONE TIMES
MOV A,M             //MOVES THE NUMBER TO ACC
ANI 01          //PERFORMING LOGICAL AND OPERATION WITH 01           //ANI 80
JNZ L1
INR E           //EVEN COUNT INCREMENT
JMP L2
L1:INR D           //ODD COUNT INCREMENT
L2:DCR B        //B COUNT DECREASES
JNZ L3          //DECRESES UNTIL BECOMES 0
MOV A,E         //EVEN COUNT LOADS\
STA FF01H
MOV A,D         //ODD COUNT LOADS
STA FF02H
HLT