//Subtract 2 8-bit numbers
F000: 45    //1ST 8 BIT NUMBER
F001: 22    //2ND 8 Bit NUMBER
F002: 23    //DIFFERENCE
F003: 00    //BORROW

//NOW THE CODE PART
LXI H,F000H     //HL REGISTER PAIR POINTING TO THE F000H ADDRESS
MOV A,M         //PUT THE VALUE OF THE MEMORY IN ACCUMULATOR
INX H          //NOW HL REGISTERT PAIR POINTS TO THE NEXT ADDRESS
MOV B,M         //PUT THE VALUE OF MEMORY IN B REGISTER
MVI C,00        //PUT THE VALUE 00 DIRECTLY TO THE C REGISTER
SUB B           //SUBTRACT THE VALUE OF B FROM THE ACCUMULATOR
JNC L1          //JUMP IF CARRY TO LABEL L1
MVI C,01        //MOVE IMMIDIATE VALUE 01 TO C REGISTER
CMA             //COMPLIMENT OF THE VALUE IN THE ACCUMULATOR
ADI 01          //ADD 01 WITH ACCUMULATOR
L1: STA F002H   //STORE THE VALUE OF ACCUMULATOR IN F002H
MOV A,C         //MOVE THE VALUE OF C REGISTER TO THE A REGISTER
STA F003H       //STORE THE VALUE OF ACCUMULATOR IN F003H
HLT             //END OF THE PROGRAM