//sum of n 8bit numbers

F000: 4     //NUMBER OF ELEMENTS
F001: 09    H
F002: F2    
F003: 10
F004: F6

FF00:01   //LOWER NIBBLE
FF01:02  //HIGHER NIBBLE

//CODE
LXI H,F000H
MOV B,M         //STORES NUMBER OF ELEMENTS
MVI A,00
MVI C,00
L2:INX H           //GOES TO THE FIRST NUMBER INPUT
ADD M           //ACC = ACC + MEMORY
JNC L1
INR C           //FOR STORING CARRIES
L1:DCR B
JNZ L2      `   //B DECREMENTS UNTIL BECOMES 0
STA FF00H       //SHOWS THE LOWER NIBBLE
MOV A,C         //FOR CARRY
STA FF01H       //SHOWS THE CARRY OR UPPER NIBBLE
HLT